<?xml version="1.0" encoding="utf-8"?>
<Database Name="Conferenceware" Class="ConferencewareDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local);Initial Catalog=Conferenceware;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ConferencewareConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Attendees" Member="Attendees">
    <Type Name="Attendee">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="food_choice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tshirt_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Attendee_EventsAttendee" Member="EventsAttendees" ThisKey="person_id" OtherKey="attendee_id" Type="EventsAttendee" />
      <Association Name="Attendee_MechManiaTeam" Member="MechManiaTeams" ThisKey="person_id" OtherKey="member1_id" Type="MechManiaTeam" />
      <Association Name="Attendee_MechManiaTeam1" Member="MechManiaTeams1" ThisKey="person_id" OtherKey="member2_id" Type="MechManiaTeam" />
      <Association Name="Attendee_MechManiaTeam2" Member="MechManiaTeams2" ThisKey="person_id" OtherKey="member3_id" Type="MechManiaTeam" />
      <Association Name="TShirtSize_Attendee" Member="TShirtSize" ThisKey="tshirt_id" OtherKey="id" Type="TShirtSize" IsForeignKey="true" />
      <Association Name="Food_Attendee" Member="Food" ThisKey="food_choice_id" OtherKey="id" Type="Food" IsForeignKey="true" />
      <Association Name="People_Attendee" Member="People" ThisKey="person_id" OtherKey="id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TShirtSizes" Member="TShirtSizes">
    <Type Name="TShirtSize">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="TShirtSize_Attendee" Member="Attendees" ThisKey="id" OtherKey="tshirt_id" Type="Attendee" />
    </Type>
  </Table>
  <Table Name="dbo.EventsAttendees" Member="EventsAttendees">
    <Type Name="EventsAttendee">
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="attendee_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Attendee_EventsAttendee" Member="Attendee" ThisKey="attendee_id" OtherKey="person_id" Type="Attendee" IsForeignKey="true" />
      <Association Name="Event_EventsAttendee" Member="Event" ThisKey="event_id" OtherKey="id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EventsSpeakers" Member="EventsSpeakers">
    <Type Name="EventsSpeaker">
      <Column Name="event_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="speaker_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Speaker_EventsSpeaker" Member="Speaker" ThisKey="speaker_id" OtherKey="person_id" Type="Speaker" IsForeignKey="true" />
      <Association Name="Event_EventsSpeaker" Member="Event" ThisKey="event_id" OtherKey="id" Type="Event" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Foods" Member="Foods">
    <Type Name="Food">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Food_Attendee" Member="Attendees" ThisKey="id" OtherKey="food_choice_id" Type="Attendee" />
    </Type>
  </Table>
  <Table Name="dbo.Locations" Member="Locations">
    <Type Name="Location">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="max_capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="building_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="room_number" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="notes" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Location_Event" Member="Events" ThisKey="id" OtherKey="location_id" Type="Event" />
    </Type>
  </Table>
  <Table Name="dbo.Speakers" Member="Speakers">
    <Type Name="Speaker">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Speaker_EventsSpeaker" Member="EventsSpeakers" ThisKey="person_id" OtherKey="speaker_id" Type="EventsSpeaker" />
      <Association Name="People_Speaker" Member="People" ThisKey="person_id" OtherKey="id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TimeSlots" Member="TimeSlots">
    <Type Name="TimeSlot">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="start_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="end_time" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="TimeSlot_Event" Member="Events" ThisKey="id" OtherKey="timeslot_id" Type="Event" />
      <Association Name="TimeSlot_VolunteerTimeSlot" Member="VolunteerTimeSlot" ThisKey="id" OtherKey="timeslot_id" Type="VolunteerTimeSlot" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.People" Member="Peoples">
    <Type Name="People">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="phone_number" Type="System.String" DbType="NChar(12) NOT NULL" CanBeNull="false" />
      <Association Name="People_Attendee" Member="Attendee" ThisKey="id" OtherKey="person_id" Type="Attendee" Cardinality="One" />
      <Association Name="People_Speaker" Member="Speaker" ThisKey="id" OtherKey="person_id" Type="Speaker" Cardinality="One" />
      <Association Name="People_Volunteer" Member="Volunteer" ThisKey="id" OtherKey="person_id" Type="Volunteer" Cardinality="One" />
      <Association Name="People_Staff" Member="Staff" ThisKey="id" OtherKey="person_id" Type="Staff" Cardinality="One" />
      <Association Name="People_CompanyPerson" Member="CompanyPerson" ThisKey="id" OtherKey="person_id" Type="CompanyPerson" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Volunteers" Member="Volunteers">
    <Type Name="Volunteer">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="is_video_trained" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Volunteer_VolunteersVolunteerTimeSlot" Member="VolunteersVolunteerTimeSlots" ThisKey="person_id" OtherKey="volunteer_id" Type="VolunteersVolunteerTimeSlot" />
      <Association Name="People_Volunteer" Member="People" ThisKey="person_id" OtherKey="id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="auth_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="People_Staff" Member="People" ThisKey="person_id" OtherKey="id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Events" Member="Events">
    <Type Name="Event">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NText NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="max_attendees" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="timeslot_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="location_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_visible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Event_EventsAttendee" Member="EventsAttendees" ThisKey="id" OtherKey="event_id" Type="EventsAttendee" />
      <Association Name="Event_EventsSpeaker" Member="EventsSpeakers" ThisKey="id" OtherKey="event_id" Type="EventsSpeaker" />
      <Association Name="Location_Event" Member="Location" ThisKey="location_id" OtherKey="id" Type="Location" IsForeignKey="true" />
      <Association Name="TimeSlot_Event" Member="TimeSlot" ThisKey="timeslot_id" OtherKey="id" Type="TimeSlot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pages" Member="Pages">
    <Type Name="Page">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="page_content" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="parent_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VolunteersVolunteerTimeSlots" Member="VolunteersVolunteerTimeSlots">
    <Type Name="VolunteersVolunteerTimeSlot">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="volunteer_timeslot_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="volunteer_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_scheduled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_confirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Volunteer_VolunteersVolunteerTimeSlot" Member="Volunteer" ThisKey="volunteer_id" OtherKey="person_id" Type="Volunteer" IsForeignKey="true" />
      <Association Name="VolunteerTimeSlot_VolunteersVolunteerTimeSlot" Member="VolunteerTimeSlot" ThisKey="volunteer_timeslot_id" OtherKey="timeslot_id" Type="VolunteerTimeSlot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VolunteerTimeSlots" Member="VolunteerTimeSlots">
    <Type Name="VolunteerTimeSlot">
      <Column Name="timeslot_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="is_video" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="VolunteerTimeSlot_VolunteersVolunteerTimeSlot" Member="VolunteersVolunteerTimeSlots" ThisKey="timeslot_id" OtherKey="volunteer_timeslot_id" Type="VolunteersVolunteerTimeSlot" />
      <Association Name="TimeSlot_VolunteerTimeSlot" Member="TimeSlot" ThisKey="timeslot_id" OtherKey="id" Type="TimeSlot" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="address_line1" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="address_line2" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="city" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="state" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="zip" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="needs_power" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="priority_shipping" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Company_CompanyInvoice" Member="CompanyInvoices" ThisKey="id" OtherKey="company_id" Type="CompanyInvoice" />
      <Association Name="Company_CompanyPayment" Member="CompanyPayments" ThisKey="id" OtherKey="company_id" Type="CompanyPayment" />
      <Association Name="Company_CompanyPerson" Member="CompanyPersons" ThisKey="id" OtherKey="company_id" Type="CompanyPerson" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyInvoiceItems" Member="CompanyInvoiceItems">
    <Type Name="CompanyInvoiceItem">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="invoice_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="cost" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Association Name="CompanyInvoice_CompanyInvoiceItem" Member="CompanyInvoice" ThisKey="invoice_id" OtherKey="id" Type="CompanyInvoice" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyInvoices" Member="CompanyInvoices">
    <Type Name="CompanyInvoice">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="last_sent" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="paid" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="marked_paid_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CompanyInvoice_CompanyInvoiceItem" Member="CompanyInvoiceItems" ThisKey="id" OtherKey="invoice_id" Type="CompanyInvoiceItem" />
      <Association Name="Company_CompanyInvoice" Member="Company" ThisKey="company_id" OtherKey="id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyPayments" Member="CompanyPayments">
    <Type Name="CompanyPayment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="received_date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="amount" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="comments" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Company_CompanyPayment" Member="Company" ThisKey="company_id" OtherKey="id" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.CompanyPeople" Member="CompanyPersons">
    <Type Name="CompanyPerson">
      <Column Name="person_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="company_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="is_contact" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_attending" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="is_alum" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Company_CompanyPerson" Member="Company" ThisKey="company_id" OtherKey="id" Type="Company" IsForeignKey="true" />
      <Association Name="People_CompanyPerson" Member="People" ThisKey="person_id" OtherKey="id" Type="People" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MechManiaTeams" Member="MechManiaTeams">
    <Type Name="MechManiaTeam">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="team_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="member1_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member2_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member3_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="account_name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="account_password" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="Attendee_MechManiaTeam" Member="Attendee" ThisKey="member1_id" OtherKey="person_id" Type="Attendee" IsForeignKey="true" />
      <Association Name="Attendee_MechManiaTeam1" Member="Attendee1" ThisKey="member2_id" OtherKey="person_id" Type="Attendee" IsForeignKey="true" />
      <Association Name="Attendee_MechManiaTeam2" Member="Attendee2" ThisKey="member3_id" OtherKey="person_id" Type="Attendee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>