//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Conferenceware.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ControllerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ControllerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Conferenceware.Localization.ControllerStrings", typeof(ControllerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only PNG images are allowed.
        /// </summary>
        internal static string SettingsController_Error_OnlyPNGAllowed {
            get {
                return ResourceManager.GetString("SettingsController_Error_OnlyPNGAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration must be closed before the end of the conference.
        /// </summary>
        internal static string SettingsController_Error_RegistrationMustOccurBeforeEnd {
            get {
                return ResourceManager.GetString("SettingsController_Error_RegistrationMustOccurBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date must occur before end date.
        /// </summary>
        internal static string SettingsController_Error_StartMustOccurBeforeEnd {
            get {
                return ResourceManager.GetString("SettingsController_Error_StartMustOccurBeforeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time cannot occur after conference end (can change in settings).
        /// </summary>
        internal static string TimeSlotController_Error_EndAfterConferenceEnd {
            get {
                return ResourceManager.GetString("TimeSlotController_Error_EndAfterConferenceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time cannot be before conference starts (can change in settings).
        /// </summary>
        internal static string TimeSlotController_Error_StartBeforeConferenceStart {
            get {
                return ResourceManager.GetString("TimeSlotController_Error_StartBeforeConferenceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time must be before end time.
        /// </summary>
        internal static string TimeSlotController_Error_StartBeforeEnd {
            get {
                return ResourceManager.GetString("TimeSlotController_Error_StartBeforeEnd", resourceCulture);
            }
        }
    }
}
